w3c/resource-timing

- index.html
This is continuation of w3c/performance-timeline#7.
- added Worker references in processing section
- cleaned up description to not limit RT to "current page"
/cc @plehegar I think this is all we need in this one, can you sanity check? Anything I'm missing?
> Make RT "worker friendly"

- index.html
- fetches that are blocked (CSP, CORS, etc) are omitted
- fetches aborted due to network/other errors must be included
- failed fetches must surface initialized attributes up to point of
failure
Closes #12.
> Surface failed fetches in the performance timeline

- index.html
Addresses feedback in https://bugzilla.mozilla.org/show_bug.cgi?id=1154309#c49: 
- use `unsigned long` for *Size attributes
- clarify that *Size attributes are subject to TAO
> Size attributes: switch to unsigned long, and clarify TAO restrictions

- index.html
Shuffled text to have a proper terminology section.
Added "current document" definition.
Removed reference to HR-TIME and replaced with HR-TIME-2
> Terminology

- index.html
- spell out cache vs network fetch behavior
- notes for non-2xx responses
closes #40
> clarify {transfer,encodedBody,decodedBody}size

- index.html
One of the links towards the fetch spec was accidentally defined in markdown. Changed to an HTML link :)
> Fix up a link towards the Fetch spec

- index.html
Closes https://github.com/w3c/resource-timing/issues/43
As currently defined and used, it is not clear what should happen when a timing-allow-check is run on a same-origin resource. This PR defines that the check should pass for same-origin resources.
> timing-allow-check handling of same-origin resources

- index.html
Background: https://github.com/w3c/resource-timing/issues/62
This change allows a list of origins to be provided via a comma
separated list, or via multiple headers (which have equivalent
semantics). The "timing allow check algorithm" is also updated
to support list semantics.
Preview: https://cdn.rawgit.com/w3c/resource-timing/fix-tao/index.html#timing-allow-origin
> Change TAO to support comma separated field values

- index.html
Based on the discussion earlier today on the webperf call...
- Added: `fetch`, `beacon`, `navigation` as valid values. The last case is
important for ServiceWorker cases; Nav Timing 2 will report same
value.
- If none of the specified cases match, the default fallback is `other`.
Closes https://github.com/w3c/resource-timing/issues/69.
> Clarify initiatorType

- index.html
Closes https://github.com/w3c/resource-timing/issues/55.
@yoavweiss @toddreifsteck @plehegar ptal.
> Recommendation for when add/queue steps should run

- index.html
Discussion:
- https://github.com/w3c/resource-timing/issues/63
- https://www.w3.org/2016/11/30-webperf-minutes.html
Closes https://github.com/w3c/resource-timing/issues/63.
> clarify responseStart

- index.html
This should fix #99
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/resource-timing/abnf.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/resource-timing/177e382...88cf7ca.html)
> ABNF uses list extension

- index.html
***
[Preview](https://s3.amazonaws.com/pr-preview/marcoscaceres/resource-timing/toJSON.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/resource-timing/b524748...marcoscaceres:1ab6100.html)
> fix: define toJSON (closes #112)

- index.html
Currently `connectEnd` is defined as the time after the UA started establishing a connection, which seems wrong. As an implementer, I'd interpret that as the time after a `connect()` call was called, which is wrong for non-blocking sockets.
The PR fixes that to clarify that it should be the timestamp after the connection finished.
***
[Preview](https://s3.amazonaws.com/pr-preview/yoavweiss/resource-timing/gh-pages.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/resource-timing/fbdf3e0...yoavweiss:1ae302d.html)
> Fix `connectEnd` definition

- index.html
This change adds consistency to the substep descriptions (all now start in uppercase), fixes a linking error for resourcetimingbufferfull, and fixes https://github.com/w3c/resource-timing/issues/134
***
<a href="https://pr-preview.s3.amazonaws.com/npm1/resource-timing/pull/136.html" title="Last updated on Jan 3, 2018, 10:23 PM GMT (c00751f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/136/68372fd...npm1:c00751f.html" title="Last updated on Jan 3, 2018, 10:23 PM GMT (c00751f)">Diff</a>
> Fix substeps ordering when buffer is full

- index.html
Fixes https://github.com/w3c/resource-timing/issues/95
@tdresser 
@igrigorik 
@marcoscaceres
***
<a href="https://pr-preview.s3.amazonaws.com/npm1/resource-timing/pull/146.html" title="Last updated on Mar 15, 2018, 5:07 AM GMT (dadab1b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/146/38b4edb...npm1:dadab1b.html" title="Last updated on Mar 15, 2018, 5:07 AM GMT (dadab1b)">Diff</a>
> Clarify addition of PerformanceResourceTiming

- .travis.yml
- W3CTRMANIFEST
- index.html
This PR changes the `gh-pages` branch to be focused back on Resource Timing Level 2 instead of Level 3.
This is to address https://github.com/w3c/resource-timing/issues/131 and unblock https://github.com/w3c/resource-timing/pull/150#issuecomment-375805896.
We have not yet made any Level 3-specific changes to `gh-pages`, and would like to revert `gh-pages` back to a Level 2 workspace.
The two branches diverged at fe2795dea6882557265c925d288cb34ef84b6eeb:
```
>git merge-base origin/gh-pages origin/V2
fe2795dea6882557265c925d288cb34ef84b6eeb
```
```
>git show fe2795dea6882557265c925d288cb34ef84b6eeb
commit fe2795dea6882557265c925d288cb34ef84b6eeb
Merge: 64d7eed c65d290
Author: Todd Reifsteck <toddreif@microsoft.com>
Date:   Wed Dec 14 10:14:46 2016 -0800
Merge pull request #83 from …
```
> Changes spec back to Level 2

- index.html
As requested in issue #148.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/150.html" title="Last updated on Apr 24, 2018, 7:58 PM GMT (2414dd1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/150/784d351...2414dd1.html" title="Last updated on Apr 24, 2018, 7:58 PM GMT (2414dd1)">Diff</a>
> Remove mention of default actions.

- index.html
Small fix for https://github.com/w3c/resource-timing/issues/154
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/156.html" title="Last updated on May 17, 2018, 12:54 PM GMT (fedec69)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/156/0b6e799...fedec69.html" title="Last updated on May 17, 2018, 12:54 PM GMT (fedec69)">Diff</a>
> Fix 'underlined' -> 'in parenthesis'

- index.html
I'd like to propose a modest change to the "recommended" initial UA RT buffer size of 150.
I've been doing some [research](https://nicj.net/resourcetiming-visibility-third-party-scripts-ads-and-page-weight/) into various aspects of ResourceTiming "visibility", and have found that over 14% of sites generate more than 150 resources in their main frame.
Here's a distribution of the Alexa Top 1000 sites and how many RT entries are from their main frame (from a [crawl](https://github.com/nicjansma/resourcetiming-visibility) with the buffer size increased in the head):
In this crawl, ~18% of sites would have hit the 150 limit (and only 15% of _those_ sites set the buffer size higher).
The 150 number is a UA-recommended limit, though I believe all current UAs choose 150.  It is not a spec …
> Update recommended min UA Resource Timing buffer size to 250

- index.html
Closes #122
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/159.html" title="Last updated on Jun 15, 2018, 9:59 AM GMT (de148c0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/159/0b6e799...yoavweiss:de148c0.html" title="Last updated on Jun 15, 2018, 9:59 AM GMT (de148c0)">Diff</a>
> Add nextHopProtocol HTTP/0.9 and 1.0. Link to QUIC

- index.html
Fixup linking - remove some badness (e.g., reference to WebIDL-1 and HTML5).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/170.html" title="Last updated on Oct 11, 2018, 7:11 AM GMT (b2a5f02)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/170/de1f8b5...b2a5f02.html" title="Last updated on Oct 11, 2018, 7:11 AM GMT (b2a5f02)">Diff</a>
> editorial: update links

- index.html
Small editorial nits.
@marcoscaceres can you take look?
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/171.html" title="Last updated on Oct 11, 2018, 10:43 AM GMT (188fa42)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/171/cd2e3ec...yoavweiss:188fa42.html" title="Last updated on Oct 11, 2018, 10:43 AM GMT (188fa42)">Diff</a>
> Removed ! from performance entry buffer links

- index.html
To register the Timing-Allow-Origin header.
***
<a href="https://pr-preview.s3.amazonaws.com/siusin/resource-timing/pull/176.html" title="Last updated on Oct 24, 2018, 4:14 PM GMT (9c003da)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/176/cc2e16e...siusin:9c003da.html" title="Last updated on Oct 24, 2018, 4:14 PM GMT (9c003da)">Diff</a>
> add iana consideration section

- index.html
> Better define which entries are exposed for nested contexts

- index.html
This change adds the call to register the "resource" entryType.
***
<a href="https://pr-preview.s3.amazonaws.com/npm1/resource-timing/pull/181.html" title="Last updated on Nov 29, 2018, 11:18 PM GMT (24b7810)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/181/48660ad...npm1:24b7810.html" title="Last updated on Nov 29, 2018, 11:18 PM GMT (24b7810)">Diff</a>
> Register entry type "resource"

- index.html
@cvazac pointed out that the current algorithm is incorrect. This fixes it.
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/184.html" title="Last updated on Dec 12, 2018, 4:35 PM GMT (7b74e0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/184/c94bdee...yoavweiss:7b74e0c.html" title="Last updated on Dec 12, 2018, 4:35 PM GMT (7b74e0c)">Diff</a>
> Fix "can add entry" algorithm typo which made it incorrect

- index.html
closes https://github.com/w3c/resource-timing/issues/123
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/189.html" title="Last updated on Dec 19, 2018, 4:40 PM UTC (536548a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/189/13d5a2e...yoavweiss:536548a.html" title="Last updated on Dec 19, 2018, 4:40 PM UTC (536548a)">Diff</a>
> Clarify that connectStart/connectEnd refer to the latest connection retry

- index.html
Closes https://github.com/w3c/resource-timing/issues/120
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/187.html" title="Last updated on Dec 18, 2018, 1:47 PM UTC (a419108)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/187/13d5a2e...yoavweiss:a419108.html" title="Last updated on Dec 18, 2018, 1:47 PM UTC (a419108)">Diff</a>
> Address the request retry case, and add a note

- index.html
Closes #160 
As discussed on the call, this is not currently testable in WPT infrastructure. I'm planning to open an issue to keep track of tests for this.
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/185.html" title="Last updated on Dec 19, 2018, 11:24 PM UTC (78bd09f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/185/13d5a2e...yoavweiss:78bd09f.html" title="Last updated on Dec 19, 2018, 11:24 PM UTC (78bd09f)">Diff</a>
> Connection reuse does not imply DNS was not required

- index.html
@yoavweiss This got renamed formally in draft 17.
***
<a href="https://pr-preview.s3.amazonaws.com/LPardue/resource-timing/pull/191.html" title="Last updated on Jan 3, 2019, 1:44 PM UTC (ce58d8e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/191/3e08125...LPardue:ce58d8e.html" title="Last updated on Jan 3, 2019, 1:44 PM UTC (ce58d8e)">Diff</a>
> HTTP over QUIC is now HTTP/3

- index.html
As @npm1 pointed out, we can handwave our way around the issues pointed out in https://github.com/w3c/resource-timing/issues/173 and #152 by applying TAO check to all related fetches, rather than just the last non-redirected one (in a handwavy way, but better than nothing).
Some tests for this are at https://github.com/web-platform-tests/wpt/pull/13518. I'll add more.
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/196.html" title="Last updated on Jan 10, 2019, 4:49 PM UTC (43fc224)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/196/47f8c68...yoavweiss:43fc224.html" title="Last updated on Jan 10, 2019, 4:49 PM UTC (43fc224)">Diff</a>
> Force TAO check on all fetches, not just the last non-redirected one

- index.html
Supersedes https://github.com/w3c/resource-timing/pull/172 and improves on https://github.com/w3c/resource-timing/pull/196 by aligning with the CORS model, even if in a handwavy way for now.
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/197.html" title="Last updated on Feb 11, 2019, 7:22 PM UTC (db31e5a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/197/9b75d42...yoavweiss:db31e5a.html" title="Last updated on Feb 11, 2019, 7:22 PM UTC (db31e5a)">Diff</a>
> Improve TAO definition

- index.html
fixes #212 
This is a temporary fix for the ReSpec warnings... once we get HR-TIME2 into Shepherd, we can remove the cited definition of DOMHighResTimeStamp from this spec.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/213.html" title="Last updated on Jun 26, 2019, 4:51 AM UTC (2289ff7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/213/a60857f...2289ff7.html" title="Last updated on Jun 26, 2019, 4:51 AM UTC (2289ff7)">Diff</a>
> fix: small xref fixes

- index.html
Closes #199 with @davidben's text from https://github.com/w3c/resource-timing/issues/199#issuecomment-542943300
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/219.html" title="Last updated on Jan 22, 2020, 7:56 AM UTC (2fde8ab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/219/73ad478...yoavweiss:2fde8ab.html" title="Last updated on Jan 22, 2020, 7:56 AM UTC (2fde8ab)">Diff</a>
> Zero RTT clarifications from davidben

- index.html
Use the timing allow passed flag, once it lands in Fetch.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/218.html" title="Last updated on Feb 14, 2020, 8:33 PM UTC (58040d9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/218/70baa57...58040d9.html" title="Last updated on Feb 14, 2020, 8:33 PM UTC (58040d9)">Diff</a>
> Update timing allow check algorithm

- index.html
Fixes https://github.com/w3c/resource-timing/issues/215
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/232.html" title="Last updated on Sep 15, 2020, 2:14 PM UTC (392598d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/232/20c9fb8...392598d.html" title="Last updated on Sep 15, 2020, 2:14 PM UTC (392598d)">Diff</a>
> Add task source to queue a task

- index.html
- Remove duplicates that are moved to FETCH
- Add an exported algorithm to mark resource timing
See https://github.com/whatwg/fetch/pull/1185 and https://github.com/w3c/resource-timing/issues/252
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/261.html" title="Last updated on Apr 2, 2021, 6:15 AM UTC (ce74048)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/261/bd74994...ce74048.html" title="Last updated on Apr 2, 2021, 6:15 AM UTC (ce74048)">Diff</a>
> Prepare for FETCH integration

- index.html
transferSize is based on the cache mode of the resource.
Closes #238
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/266.html" title="Last updated on Apr 15, 2021, 6:02 AM UTC (27c8bda)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/266/7c535a9...27c8bda.html" title="Last updated on Apr 15, 2021, 6:02 AM UTC (27c8bda)">Diff</a>
> Expose transferSize, encodedBodySize, decodedBodySize

- index.html
closes #277 
Recreated #277 because of all the conflicts.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/281.html" title="Last updated on Jul 7, 2021, 1:15 AM UTC (e71ab98)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/281/edea639...e71ab98.html" title="Last updated on Jul 7, 2021, 1:15 AM UTC (e71ab98)">Diff</a>
> Change nextHopProtocol to a ByteString

- .github/workflows/auto-publish.yml
Renamed the action, as we have scripts at the w3c that look for the file name "auto-publish.yml"
> Update and rename pr-push.yml to auto-publish.yml

- .github/workflows/tidy.yml
> chore: add tidy workflow

- index.html
Some changes to simplify source code using xrefs (see issue #280)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/287.html" title="Last updated on Aug 30, 2021, 3:06 PM UTC (12bbed6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/287/8b1427a...12bbed6.html" title="Last updated on Aug 30, 2021, 3:06 PM UTC (12bbed6)">Diff</a>
> replaced a number of data-cite with corresponding xref

- index.html
Closes #256
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/290.html" title="Last updated on Sep 29, 2021, 11:03 AM UTC (3ecbdaf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/290/11d3b0b...3ecbdaf.html" title="Last updated on Sep 29, 2021, 11:03 AM UTC (3ecbdaf)">Diff</a>
> Make 4.2 non-normative

- index.html
Closes #235
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/295.html" title="Last updated on Sep 29, 2021, 1:03 PM UTC (d86b900)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/295/35a3ec0...d86b900.html" title="Last updated on Sep 29, 2021, 1:03 PM UTC (d86b900)">Diff</a>
> Remove unused 'current time' definition

- index.html
I noticed two small formatting things:
- There were two 'note' sections for the initiatorType table
- There was a missing closing 'section' tag leading to a bunch of sections accidentally getting put under "Cross-origin Resources"
This PR fixes those issues.
***
<a href="https://pr-preview.s3.amazonaws.com/tommckee1/resource-timing/pull/305.html" title="Last updated on Nov 30, 2021, 4:55 PM UTC (05c43bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/305/cccbc3c...tommckee1:05c43bd.html" title="Last updated on Nov 30, 2021, 4:55 PM UTC (05c43bd)">Diff</a>
> Small formatting tweaks

- index.html
The current link goes to the HR-TIME spec but the URL fragment was missing a prefix so it didn't auto-scroll to the targeted definition.
***
<a href="https://pr-preview.s3.amazonaws.com/tommckee1/resource-timing/pull/308.html" title="Last updated on Jan 10, 2022, 5:43 PM UTC (64e53b2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/308/1d747a0...tommckee1:64e53b2.html" title="Last updated on Jan 10, 2022, 5:43 PM UTC (64e53b2)">Diff</a>
> Fix a link to the HR-TIME spec

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/310.html" title="Last updated on Jan 12, 2022, 4:05 AM UTC (2367c71)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/310/c6ad017...yoavweiss:2367c71.html" title="Last updated on Jan 12, 2022, 4:05 AM UTC (2367c71)">Diff</a>
> Clean up unused definitions and other respec errors

- index.html
Tidy is now failing due to a missing section. This adds it.
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/312.html" title="Last updated on Jan 12, 2022, 3:24 PM UTC (af8074d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/312/3b51fc4...yoavweiss:af8074d.html" title="Last updated on Jan 12, 2022, 3:24 PM UTC (af8074d)">Diff</a>
> Fix up a missing section

- index.html
Although the 'note' is non-normative, it's helpful for folks to see a more comprehensive list, IMO.
LMKWYT!
***
<a href="https://pr-preview.s3.amazonaws.com/tommckee1/resource-timing/pull/311.html" title="Last updated on Jan 13, 2022, 2:36 PM UTC (4219593)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/311/dc1f469...tommckee1:4219593.html" title="Last updated on Jan 13, 2022, 2:36 PM UTC (4219593)">Diff</a>
> List all the attributes that will get masked when TAO fails

- .github/workflows/auto-publish.yml
When looking into why RT is not auto-published, it seems like the cause is the spec status that's an editor's draft. NT seems to get over the same issue by overriding the spec status, so trying the same here
> Override spec status for auto-publishing

- index.html
Closes https://github.com/w3c/resource-timing/issues/317
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/318.html" title="Last updated on Jan 25, 2022, 5:15 PM UTC (6e4cbad)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/318/b5d09c9...6e4cbad.html" title="Last updated on Jan 25, 2022, 5:15 PM UTC (6e4cbad)">Diff</a>
> Editorial: Remove 'relevant application caches'

- index.html
~~Just a minor typo fix :)~~ this was fixed before this could be merged, so now just clarity improvement
Aside, this sentence was a bit hard for me to parse. Is something like...
> Though the <a>PerformanceResourceTiming</a> interface gives timing information for resources in a document, the load event on resources can already measure timing to determine cache hits and misses in a limited fashion, and the cross-origin restrictions in [=/HTTP Fetch=] prevent the leakage of any additional information.
1. Accurate?
2. A possible alternative that could be considered?
***
<a href="https://pr-preview.s3.amazonaws.com/patrickhulce/resource-timing/pull/307.html" title="Last updated on Jan 27, 2022, 4:22 PM UTC (9dd0b6d)">Preview</a> | <a …
> Minor clarity improvement in Privacy & Security section

- index.html
Make it clear that resource timing reflects fetches of HTTP(s) resources,
which is a more accurate term than "downloadable".
Closes #100
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/324.html" title="Last updated on Apr 11, 2022, 12:43 PM UTC (c37883c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/324/66b113a...c37883c.html" title="Last updated on Apr 11, 2022, 12:43 PM UTC (c37883c)">Diff</a>
> Clarify "downloadable"

- index.html
As part of https://github.com/whatwg/fetch/pull/1413
Those numbers are per-response and not per-fetch, so they need to be
treated separately.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/321.html" title="Last updated on Jun 17, 2022, 2:46 PM UTC (9cf8453)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/321/148c98c...9cf8453.html" title="Last updated on Jun 17, 2022, 2:46 PM UTC (9cf8453)">Diff</a>
> Use `response body info` instead of `timing info` for body sizes

- index.html
Missing a closing curly.
https://w3c.github.io/resource-timing/#sec-cross-origin-resources
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/337.html" title="Last updated on Jul 18, 2022, 2:42 PM UTC (817406e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/337/147d0fc...817406e.html" title="Last updated on Jul 18, 2022, 2:42 PM UTC (817406e)">Diff</a>
> chore: Fix missing curly brace

- index.html
Introducing a render blocking status field. (https://github.com/w3c/resource-timing/issues/262)
Fetch changes : https://github.com/whatwg/fetch/pull/1449
~~HTML changes: https://github.com/whatwg/html/pull/7979~~
Explainer : https://github.com/abinpaul1/resource-timing/blob/render-blocking-status-explainer/Explainer/Render_Blocking_Status.md
***
<a href="https://pr-preview.s3.amazonaws.com/abinpaul1/resource-timing/pull/327.html" title="Last updated on Aug 10, 2022, 6:11 PM UTC (41acb22)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/327/e71c2ab...abinpaul1:41acb22.html" title="Last updated on Aug 10, 2022, 6:11 PM UTC (41acb22)">Diff</a>
> Add Render Blocking Status to PerformanceResourceTiming

- index.html
Introducing HTTP response status code. (https://github.com/w3c/resource-timing/issues/90)
Fetch changes : https://github.com/whatwg/fetch/pull/1468
Explainer : https://github.com/abinpaul1/resource-timing/blob/explainer-resource-response-status/Explainers/Response_Status_Code.md
***
<a href="https://pr-preview.s3.amazonaws.com/abinpaul1/resource-timing/pull/335.html" title="Last updated on Oct 24, 2022, 4:46 PM UTC (053cf41)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/335/958ccdd...abinpaul1:053cf41.html" title="Last updated on Oct 24, 2022, 4:46 PM UTC (053cf41)">Diff</a>
> Add response status code to PerfomanceResourceTiming

- index.html
even with the presence of TAO header fields.  This resolves https://github.com/w3c/resource-timing/issues/342
***
<a href="https://pr-preview.s3.amazonaws.com/achristensen07/resource-timing/pull/369.html" title="Last updated on Jan 26, 2023, 8:08 PM UTC (01dafaf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/369/85e74ce...achristensen07:01dafaf.html" title="Last updated on Jan 26, 2023, 8:08 PM UTC (01dafaf)">Diff</a>
> Allow user agents to enforce cross-origin restrictions

- index.html
Addresses #332.
This defines a concept of "delivery type" which currently describes the difference between resources delivered from the HTTP cache and those not (currently only detectable via transferSize). It is expected to be extended to describe resources delivered from other stores, such as the consuming resources from the HTML preload buffer and navigational prefetches.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/resource-timing/pull/343.html" title="Last updated on Mar 10, 2023, 4:06 PM UTC (78dc701)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/343/98b0e13...jeremyroman:78dc701.html" title="Last updated on Mar 10, 2023, 4:06 PM UTC (78dc701)">Diff</a>
> Add delivery type to PerformanceResourceTiming.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/383.html" title="Last updated on Feb 8, 2024, 10:13 AM UTC (e2720dd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/383/23da0c2...e2720dd.html" title="Last updated on Feb 8, 2024, 10:13 AM UTC (e2720dd)">Diff</a>
> WebIDL fix: initialize PerformanceEntry instead of shadowing

- index.html
Closes #386
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/387.html" title="Last updated on Apr 26, 2024, 3:04 PM UTC (0226ea5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/387/c75a9f5...0226ea5.html" title="Last updated on Apr 26, 2024, 3:04 PM UTC (0226ea5)">Diff</a>
> Correct clarification for data: URIs

- index.html
Fixes a few broken refs: "default toJSON operation", Performance and navigation timing startTime refs.
Closes: #376
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/390.html" title="Last updated on May 24, 2024, 6:26 PM UTC (53ad617)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/390/3d7c3f5...53ad617.html" title="Last updated on May 24, 2024, 6:26 PM UTC (53ad617)">Diff</a>
> Fix broken references

- index.html
RFC7230 is replaced with RFC9110; update the reference to list ABNF syntax accordingly
Closes: #404
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/406.html" title="Last updated on Aug 30, 2024, 2:46 AM UTC (c558a4f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/406/1cb5bd3...c558a4f.html" title="Last updated on Aug 30, 2024, 2:46 AM UTC (c558a4f)">Diff</a>
> Fix broken reference to RFC7230

- index.html
responseStart now returns `firstInterimResponseStart` as before, but falls back to `finalResponseHeadersStart` if there is no interim response.
Closes #345
> Add finalResponseHeadersStart which is always the 2xx/4xx/5xx response.
