w3c/resource-timing

index.html
=> Exclude no-cors cross-origin stylesheet subresources

index.html
See https://github.com/w3c/resource-timing/issues/25.
=> set responseEnd if connection is terminated

index.html
moving the note from nav timing.
=> Added a note on requestEnd

.travis.yml, W3CTRMANIFEST
update the Level 2 spec for new commits on V2 branches
=> set up auto-pub on V2

CONTRIBUTING.md, LICENSE, index.html
Reduce insecure URLs in `respecConfig` and elsewhere.
=> More HTTP -> HTTPS

index.html
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/resource-timing/v2.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/resource-timing/9db1c6f...513baf8.html)
=> update the editor's draft for v2

index.html
* closes #107
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/157.html" title="Last updated on May 18, 2018, 4:08 AM GMT (f70ebea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/157/33d5be9...f70ebea.html" title="Last updated on May 18, 2018, 4:08 AM GMT (f70ebea)">Diff</a>
=> fix xref to PerformanceEntry

index.html
Closes #70
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/192.html" title="Last updated on Jan 4, 2019, 9:42 AM UTC (fd59a9d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/192/3e08125...yoavweiss:fd59a9d.html" title="Last updated on Jan 4, 2019, 9:42 AM UTC (fd59a9d)">Diff</a>
=> Remove issue 27 and mark exclusion at risk

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/193.html" title="Last updated on Jan 4, 2019, 9:48 AM UTC (4042b20)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/193/3e08125...yoavweiss:4042b20.html" title="Last updated on Jan 4, 2019, 9:48 AM UTC (4042b20)">Diff</a>
=> Add myself to the editors list

index.html
Closes #201
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/206.html" title="Last updated on Apr 24, 2019, 6:50 PM UTC (396be56)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/206/7f033b2...yoavweiss:396be56.html" title="Last updated on Apr 24, 2019, 6:50 PM UTC (396be56)">Diff</a>
=> Clarify TAO processing when it comes to revalidation responses

index.html
Closes #207
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/214.html" title="Last updated on Sep 23, 2019, 9:04 AM UTC (5cd00eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/214/3cbb8cc...yoavweiss:5cd00eb.html" title="Last updated on Sep 23, 2019, 9:04 AM UTC (5cd00eb)">Diff</a>
=> Align TAO processing with CORS

index.html
Closes #118
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/217.html" title="Last updated on Nov 28, 2019, 3:47 PM UTC (7d5ad55)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/217/70baa57...yoavweiss:7d5ad55.html" title="Last updated on Nov 28, 2019, 3:47 PM UTC (7d5ad55)">Diff</a>
=> Protect workerStart with a TAO check

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/234.html" title="Last updated on Sep 15, 2020, 3:00 PM UTC (9b187dd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/234/ada912e...9b187dd.html" title="Last updated on Sep 15, 2020, 3:00 PM UTC (9b187dd)">Diff</a>
=> Respec update

index.html
Closes #241 
/cc @toddreifsteck - as I couldn't add you to the reviewers list for some reason...
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/253.html" title="Last updated on Jan 20, 2021, 6:26 AM UTC (5710a0e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/253/05e9c1b...yoavweiss:5710a0e.html" title="Last updated on Jan 20, 2021, 6:26 AM UTC (5710a0e)">Diff</a>
=> Change editors and fixup respec errors

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/265.html" title="Last updated on Apr 8, 2021, 8:50 AM UTC (82afd4c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/265/837ca19...82afd4c.html" title="Last updated on Apr 8, 2021, 8:50 AM UTC (82afd4c)">Diff</a>
=> Export setup function

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/268.html" title="Last updated on Apr 14, 2021, 11:51 AM UTC (8dfcae0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/268/8324333...yoavweiss:8dfcae0.html" title="Last updated on Apr 14, 2021, 11:51 AM UTC (8dfcae0)">Diff</a>
=> Fix exports

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/270.html" title="Last updated on Apr 15, 2021, 6:14 AM UTC (5943205)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/270/72ff2a0...5943205.html" title="Last updated on Apr 15, 2021, 6:14 AM UTC (5943205)">Diff</a>
=> Remove stray <<< HEAD

index.html, tidyconfig.txt
Run of tidy, plus silence some ReSpec warnings.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/278.html" title="Last updated on Jul 1, 2021, 5:20 AM UTC (827d398)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/278/691955b...827d398.html" title="Last updated on Jul 1, 2021, 5:20 AM UTC (827d398)">Diff</a>
=> chore: tidy up spec

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/resource-timing/pull/288.html" title="Last updated on Aug 31, 2021, 7:43 AM UTC (663e8d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/288/861256d...yoavweiss:663e8d3.html" title="Last updated on Aug 31, 2021, 7:43 AM UTC (663e8d3)">Diff</a>
=> [chore] Fix up tidy errors

index.html
Closes #289
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/291.html" title="Last updated on Sep 29, 2021, 7:40 AM UTC (5f42eb2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/291/bb8ad36...5f42eb2.html" title="Last updated on Sep 29, 2021, 7:40 AM UTC (5f42eb2)">Diff</a>
=> Pre -> code to make links work

index.html
Informally defines possible values of initiatorType
Closes #276
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/293.html" title="Last updated on Sep 29, 2021, 10:56 AM UTC (715d91c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/293/bb8ad36...715d91c.html" title="Last updated on Sep 29, 2021, 10:56 AM UTC (715d91c)">Diff</a>
=> Bring back some non-normative notes

index.html
Closes #243
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/296.html" title="Last updated on Sep 29, 2021, 1:13 PM UTC (fe32dca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/296/6f9e648...fe32dca.html" title="Last updated on Sep 29, 2021, 1:13 PM UTC (fe32dca)">Diff</a>
=> Remove SHOULD from non-normative example

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/300.html" title="Last updated on Oct 4, 2021, 11:13 AM UTC (8095069)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/300/712fd8c...8095069.html" title="Last updated on Oct 4, 2021, 11:13 AM UTC (8095069)">Diff</a>
=> Be more specific about initiator types

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/334.html" title="Last updated on Jul 7, 2022, 7:26 AM UTC (51a96cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/334/1df3821...51a96cb.html" title="Last updated on Jul 7, 2022, 7:26 AM UTC (51a96cb)">Diff</a>
=> Update my affiliation

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/pull/339.html" title="Last updated on Jul 22, 2022, 3:09 PM UTC (bcebe2f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-timing/339/bc3ff6f...bcebe2f.html" title="Last updated on Jul 22, 2022, 3:09 PM UTC (bcebe2f)">Diff</a>
=> Add notes RE privacy IG issues
